### ISSUE TITLE
Portal issues

### ISSUE THREAD

**Issue by xfrankbx** [Zarathul/simpleportals#3]
I have 2 issues.
1: I only get a couple teleports out of a portal before it just stops.  Even with the cost set to 0.
2: When stepping into portal, It will teleport me to the other dimension I am trying to get to, except all I can see is emptiness and I can not move.
I have to use the /tpj <dim> command included with JustEnoughDimensions until I finally appear in the dimension and able to move around.
Thoughts ?

**Comment by Zarathul** [comment]
Can't reproduce that. Tested with Forge 14.22.1.2485 and JED 1.5.5, singleplayer, multiplayer, creative, survival, with and without cost. Even waited for the custom dimensions to unload. Works for me.
Maybe another conflicting mod or it has something to do with how you setup your custom dimensions. I really don't know at this point.

**Comment by xfrankbx** [comment]
Hmmm...  Welp I'll try it with out all the other mods I have loaded and see.  I'm running forge-1.11.2-13.20.1.2476 with JED 1.6.0 I've been working with the developer to get it more Sponge friendly..
But I do have a ton of other mods.  I'll disable them all, just do Forge with JED, see if that works and gradually add things back in until it breaks.
Thanks for the fast reply, I'll let ya know what I find.  Maybe you can point me in the right direction to fix if it is some sort of incompatibility with something..

Update:
Just tried it on my server.  This time I get to teleport from portal to portal without the odd limbo issue, but I only get 1 teleport.  Can't teleport back.  But if I teleport back to Dim0, then use the Portal, I get back to Dim1000 that I created with JED.
I replicated this a couple times, so I can get from Dim0 to Dim1000 via the portal, but not back.  But good thing, no more Limbo :-P LoL.
Mincraft 1.11.2
forge-1.11.2-13.20.1.2476
JED 1.6.0 - https://masa.dy.fi/tmp/minecraft/jed/1.6.0-dev/
simpleportals-1.11.2-1.4.0.0
So I also tried this, same mods as a Single Player world and it worked peachy.  But not on the server.
Thoughts ?

**Comment by xfrankbx** [comment]
Another Update.
Completely reinstalled Mincraft, on the server and on my desktop.  Same versions as before.
This time I get 3 hops through the portals, then it doesn't work anymore.  I disconnect from the server and go back in, and can hop 3 more times between portals..  Only 1 portal on Dim0 and 1 portal on Dim1000...
I just tried it again while typing this message.  and it worked 2 more times.  Is there some sort of "cool down" timer ?  I let it sit another couple minutes and tried again, and again it worked 2 more times.  So I am thinking there is some sort of "Cool down" period either created by SimplePortals or Forge ?
Now that I think it is "working" LOL, I'll start adding mods back in until it exhibits issues the original issues I wrote about.
Thanks!

**Comment by xfrankbx** [comment]
Wow, just when I thought I had it figured out..  Today I try it.. I got 3 jumps through, left it be idle for 2 mins, 5 mins, then 10 mins, and it still isn't working.  Restarted client, still not working when on the server.
I can manually /tpj 0 go back to Dim0 then oddly the portal works to get to Dim1000... But not back again, seems only 1 way now..
When last night when I first started, I had bi-directional working but with what felt like a "cool down" period ...
Thoughts ? LOL  And like I said this is bare minimum Forge, JED, and SimplePortals.

**Comment by Zarathul** [comment]
>  Is there some sort of "cool down" timer ?

Yes, but a very short one, 60 ticks which is normaly 3 seconds.

Well you are using 1.11. I did my testing yesterday in 1.12.1 using Forge 14.22.1.2485, SimplePortals 1.5.0.0 and JED 1.5.5 with the provided sample config https://pastebin.com/LpRYUNyi.
Today I tested again in 1.11.2 (forge 13.20.1.2530), both with the most recent version of JED on Curse and with the dev version. Both work. Dev version for 1.12 also works. Singleplayer or on a server, doesn't matter, works fine.

So something with your setup must be wrong. Maybe your older forge version, java version (Java 8 is mandatory at this point) or dimensions config.

**Comment by xfrankbx** [comment]
So looks like it is a problem with Sponge on why I go to Limbo ... But no idea on the ability for it to work then stop...
Since I'm using Sponge, I found Project Portals which does what I need without issue.  So, sorry for all these messages, feel free to close out this issue.

**Comment by xfrankbx** [comment]
LOL So ProjectPortals has it's own issues...  So I took my system to bare minimum again.
Server:
Java:
> java version "1.8.0_66"
> Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
> Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)
MineCraft &Mods Versions:
> MineCraft 1.11.2
> spongeforge-1.11.2-2476-6.1.0-BETA-2715
> forge-1.11.2-13.20.1.2476
> simpleportals-1.11.2-1.4.0.0.jar
> justenoughdimensions-1.11.2-1.6.0-dev.20171107.235423

JED Command to create Dimension
> /jed dimbuilder clear
> /jed dimbuilder dimtype 1100 tmpname _dim1100 false WorldProviderSurfaceJED
> /jed dimbuilder set name Creative_1100
> /jed dimbuilder set generatorName default
> /jed dimbuilder set RandomSeed -4799909556600174584
> /jed dimbuilder set keepInventory true
> /jed dimbuilder set mobGriefing false
> /jed dimbuilder set Difficulty 1
> /jed dimbuilder set SpawnX 732
> /jed dimbuilder set SpawnY 65
> /jed dimbuilder set SpawnZ 306
> /jed dimbuilder create-as 1100

Simple Portal config
> I:powerCost=0

On my desktop I installed Minecraft Launcher, Java 8.144, and installed the same Forge and mods except of course Sponge don't need on the client side.

The reason I am using the older Forge is for Sponge, because I am trying to use GriefPrevention and LuckPerms.

So with the above, I had both issues I initially stated.  Walk through portal a few times and it quits working.. Sometimes able to manually teleport between dimensions using /tpj command and enter portal which takes me to other dimensions sometimes, while at this time mostly goes to "limbo"  I can see the Sun, and moon, can't move, grayness and clouds..  If i enter /tpj <dim id> a couple times eventually it puts me there ...
LoL
I'm happy to open my server up to you to access from the internet if you want to use your desktop against it.  But I'm out of ideas to try.

**Comment by Zarathul** [comment]
I'm sorry but to be blunt, I'm not willing to invest any more time into this. To make this very clear, I don't support sponge, nerver have, never will. Also I usually don't support old versions of my mods and I definitely don't support some random old forge version. 
Still, I spent at least 2 hours testing all kinds of configurations (with up to date forge and no sponge) as mentioned in my earlier posts and I can't get a teleportation with my mod to fail.

The limbo dimensions as you call them, I got 2 or 3 of them with the test dimensions config. But they are always empty doesn't matter how often I /tpj in or out, and I don't know nearly enough about JED to tell if this is a bug or if these are meant to be empty dimensions. The dimensions that actually have terrain work always, with /tpj or my portals. Either way, this has nothing to do with my mod.

**Comment by Zarathul** [comment]
To be sure I tested a setup with sponge today. And here we go, teleportation is completely fucked up. No sponge = no problems.

**Comment by Thorf13** [comment]
I'm not using Sponge, but I seem to be having the same problem with portals not working on the home journey. I will try stripping my game of all mods but yours and Just Enough Dimensions and try again.

Is there anything else I could do to assist?

**Comment by Zarathul** [comment]
A log might help.

**Comment by Thorf13** [comment]
So I stripped everything out of my game, and tested both my current world and a new world using the following:

Minecraft 12.2
Forge 2515
JED 1.5.5
SimpleDimensions 1.5.0.0

Interestingly, I had no problems whatsoever using portals to and from the Nether and The End dimensions.

But unfortunately I encountered the same problem with my JED dimensions, in both games. It seems therefore to be very likely that there's something about JED dimensions that's causing this problem.

My setup for a JED dimension is basically exactly the same as on the mod's Curse page. At its simplest, as I used just now testing:

/jed dimbuilder clear
/jed dimbuilder dimtype 333 tmpname _dim333 false WorldProviderSurfaceJED
/jed dimbuilder set name Portal
/jed dimbuilder create-as 333

/tpj works fine to and from this dimension.

In my new test game, I can't even get the portal to work one way. In my main world's save game, they at least work on the way out. In fact, I can't even get portals to work within the main dimension in this game.

Can you point me at the log you'd need to see? Sorry, I don't know much about Minecraft's logs other than crash reports.

**Comment by Zarathul** [comment]
latest.log and/or fml-client-latest.log from the logs directory wherever minecraft is installed. You can paste the contents in a gist https://gist.github.com/ or use pastebin and post the link here.

**Comment by Thorf13** [comment]
https://gist.github.com/Thorf13/57c40e6cd93a803cb15133e924a96927

**Comment by Zarathul** [comment]
Spent about 3 hours testing and still couldn't reproduce the problem. From your logs the only difference I can see is that you're running on MacOS which shouldn't affect anything.
Sorry but I have no idea what's going on.

Tested with one/multiple JED dimensions with different WorldProviders, different orders of portal activation, porting back/forth, used /tpj, singleplayer and with server, creative and survival mode, different portal sizes, standing and lying portals.

**Comment by Thorf13** [comment]
Zarathul, this seems to have fixed it for me. Thank you so much for all the time and effort you put into this — I really appreciate it. And I love my new portal network. Seriously, well done!
