### ISSUE TITLE
question

### ISSUE THREAD

**Issue by tryolivier** [Zarathul/simpleportals#5]
hello, i want to create portals

1 in nether 1 in spawn (world) and reliate them
1 in end 1 in spawn (world) and reliate them

but I don't want players can creates portals, is it possible ??

thanks

**Comment by Zarathul** [comment]
You will have to use something like the [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker?gameCategorySlug=mc-mods&projectID=239197) mod and remove the recipes for the portal frame and power gauge. This way only server ops can spawn them in and build portals.
To make things a little easier you can use [RecipeMaker](https://minecraft.curseforge.com/projects/minetweaker-recipemaker) if you prefer a visual editor over text files.

**Comment by tryolivier** [comment]
thanks for the reply ! :)

can we create the portals with other than "Portal Frame" bloc ??

and for the corner can we use the block we want ? for exemple if I want dirt i take dirt ?

If I make a portal all in netherrack for the portal between nether and spawn (world) it will works ??

thanks ;)

**Comment by Zarathul** [comment]
> can we create the portals with other than "Portal Frame" bloc ??

No. Every block but the 4 corner blocks has to be either a portal frame or a power gauge. 

> and for the corner can we use the block we want ? for exemple if I want dirt i take dirt ?

Yes. You can use every 'simple' block (without a tile entity). Basically every block that is purely decorative. Blocks like furnaces or a pistons will not work.

>If I make a portal all in netherrack for the portal between nether and spawn (world) it will works ??

No. See the first answer. For an explanation with screenshots look [here](https://minecraft.curseforge.com/projects/simpleportals).

**Comment by tryolivier** [comment]
perfect thanks =)

i will try it ;)

good job !

**Comment by tryolivier** [comment]
the portals works good ! good job !

I don't understand how works CraftTweaker and  RecipeMaker don't works

maybe i prefer you put a permission to create a portal like this only me can create (link) them

thanks
