### ISSUE TITLE
Portal won't create

### ISSUE THREAD

**Issue by PrincessKumico** [Zarathul/simpleportals#7]
I'm on MC 1.12.2 and I made one portal in the nether and one portal in the overworld. I right click the inside face with the portal activator and nothing happens. I've made 2 portals in the overworld and I right click and nothing. It just won't make the portal.

**Comment by Zarathul** [comment]
To be absolutely sure nothing broke, I just ran a clean install with the newest forge version for 1.12.2 (14.23.5.2838) and everything works as expected. 
The only reasons why a portal wouldn't activate are: 
1. Something is in the way
2. The address blocks in the corners of the portal are tileentities (like chests or droppers)
3. The size of the frame is too big or too small

For detailed instructions how to build portals refer to https://minecraft.curseforge.com/projects/simpleportals under "Portal construction".

Technically another mod could also somehow interfere with the portal creation, although it seems unlikely.

**Comment by PrincessKumico** [comment]
Then another mod is interfering. I have the corner blocks diamond and gold blocks. Both portals are in the open. I made one on one side of my island and one on the other side and still nothing. I'll make a copy of my modpack and begin disabling mods and testing

**Comment by Zarathul** [comment]
If you gain any more insight what's going on, please let me know.
